import type { Metadata } from "next";
import { Toaster } from 'sonner';
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased h-screen w-screen`}
      >
        {children}
        <Toaster
          visibleToasts={1}
          duration={2500}
          position="top-center"
          richColors
          theme="dark"
        />
      </body>
    </html>
  );
}
